import type { LessonWorld } from "./types";

export const worlds: LessonWorld[] = [
  {
    id: "scenario01",
    title: "S01 - 本地新项目",
    description: "从零开始初始化仓库，完成第一次提交并查看历史。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s01-init",
        validatorId: "w1-init",
        title: "初始化仓库",
        instruction: "输入 git init，在本地创建 Git 仓库。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "s01-add-all",
        validatorId: "w1-add-all",
        title: "暂存所有文件",
        instruction: "输入 git add .，把当前目录改动加入暂存区。",
        commandHint: "git add .",
        riskLevel: "basic",
      },
      {
        id: "s01-commit",
        validatorId: "w1-commit",
        title: "首次提交",
        instruction: "输入 git commit -m \"first commit\"，创建第一个提交。",
        commandHint: 'git commit -m "first commit"',
        riskLevel: "basic",
      },
      {
        id: "s01-log-oneline",
        validatorId: "w1-log-oneline",
        title: "单行历史",
        instruction: "输入 git log --oneline，用简洁格式查看提交历史。",
        commandHint: "git log --oneline",
        riskLevel: "basic",
      },
      {
        id: "s01-status",
        validatorId: "w1-status",
        title: "确认状态",
        instruction: "输入 git status，确认工作区是否干净。",
        commandHint: "git status",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario02",
    title: "S02 - 日常改动提交",
    description: "完成常见的 add 与 commit 提交流程，理解 commit -am 边界。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s02-init",
        validatorId: "w5-init",
        title: "初始化",
        instruction: "输入 git init。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "s02-add-file",
        validatorId: "w5-add-file",
        title: "暂存单文件",
        instruction: "输入 git add README.md。",
        commandHint: "git add README.md",
        riskLevel: "basic",
      },
      {
        id: "s02-commit-m",
        validatorId: "w5-commit-m",
        title: "带说明提交",
        instruction: "输入 git commit -m \"init\"。",
        commandHint: 'git commit -m "init"',
        riskLevel: "basic",
      },
      {
        id: "s02-add-all",
        validatorId: "w5-add-all",
        title: "暂存全部",
        instruction: "输入 git add .（本关会模拟新的工作区改动）。",
        commandHint: "git add .",
        riskLevel: "basic",
      },
      {
        id: "s02-commit-am",
        validatorId: "w5-commit-am",
        title: "跳过 add 提交",
        instruction: "输入 git commit -am \"quick update\"，对已跟踪文件直接提交。",
        commandHint: 'git commit -am "quick update"',
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario03",
    title: "S03 - 诊断状态差异",
    description: "用 status、diff、diff --staged 诊断当前仓库状态。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s03-init",
        validatorId: "w4-init",
        title: "准备环境",
        instruction: "输入 git init 开始本关练习。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "s03-status",
        validatorId: "w4-status",
        title: "查看状态",
        instruction: "输入 git status，查看工作区与暂存区。",
        commandHint: "git status",
        riskLevel: "basic",
      },
      {
        id: "s03-diff",
        validatorId: "w4-diff",
        title: "未暂存差异",
        instruction: "输入 git diff，查看尚未暂存的改动。",
        commandHint: "git diff",
        riskLevel: "basic",
      },
      {
        id: "s03-diff-staged",
        validatorId: "w4-diff-staged",
        title: "已暂存差异",
        instruction: "先 git add README.md，再执行 git diff --staged。",
        commandHint: "git diff --staged",
        checkpoints: [
          { id: "s03-diff-staged-add", title: "先暂存 README.md", validatorId: "cp-add-readme" },
          { id: "s03-diff-staged-diff", title: "查看暂存区差异", validatorId: "cp-diff-staged" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s03-remote-v",
        validatorId: "w4-remote-v",
        title: "查看远程地址",
        instruction: "输入 git remote add origin https://github.com/demo/repo.git，再执行 git remote -v。",
        commandHint: "git remote -v",
        checkpoints: [
          { id: "s03-remote-v-add-origin", title: "先添加 origin 远程", validatorId: "cp-remote-add-origin" },
          { id: "s03-remote-v-show", title: "再查看远程列表", validatorId: "cp-remote-v" },
        ],
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario04",
    title: "S04 - 第一次推 GitHub",
    description: "连接远程仓库并完成首次 push -u。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s04-init",
        validatorId: "w2-init",
        title: "准备仓库",
        instruction: "先执行 git init，再 add/commit（可重复本关前几步命令）。",
        commandHint: "git init",
        checkpoints: [
          { id: "s04-init-init", title: "初始化仓库", validatorId: "cp-init" },
          { id: "s04-init-add", title: "执行一次 add", validatorId: "cp-add-any" },
          { id: "s04-init-commit", title: "完成一次 commit", validatorId: "cp-commit-any" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s04-branch-m",
        validatorId: "w2-branch-m",
        title: "统一默认分支",
        instruction: "输入 git branch -M main，把当前分支命名为 main。",
        commandHint: "git branch -M main",
        riskLevel: "basic",
      },
      {
        id: "s04-remote-add",
        validatorId: "w2-remote-add",
        title: "关联远程",
        instruction: "输入 git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        commandHint: "git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        riskLevel: "basic",
      },
      {
        id: "s04-push-u",
        validatorId: "w2-push-u",
        title: "首次推送",
        instruction: "输入 git push -u origin main，建立上游跟踪关系。",
        commandHint: "git push -u origin main",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario05",
    title: "S05 - 换电脑克隆同步",
    description: "掌握 clone、fetch、pull 与 pull --rebase 的同步流程。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s05-clone",
        validatorId: "w3-clone",
        title: "克隆仓库",
        instruction: "输入 git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        commandHint: "git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        riskLevel: "basic",
      },
      {
        id: "s05-fetch",
        validatorId: "w3-fetch",
        title: "拉取远端对象",
        instruction: "输入 git fetch，获取远程更新但不自动合并。",
        commandHint: "git fetch",
        riskLevel: "basic",
      },
      {
        id: "s05-pull",
        validatorId: "w3-pull",
        title: "拉取并合并",
        instruction: "输入 git pull，拉取并合并到当前分支。",
        commandHint: "git pull",
        riskLevel: "basic",
      },
      {
        id: "s05-pull-rebase",
        validatorId: "w3-pull-rebase",
        title: "拉取并变基",
        instruction: "输入 git pull --rebase，在团队约定允许时使用线性历史。",
        commandHint: "git pull --rebase",
        riskLevel: "advanced",
        riskNote: "仅在团队约定使用 rebase 时执行。",
      },
    ],
  },
  {
    id: "scenario06",
    title: "S06 - 更换远程地址",
    description: "检查 origin 并将远程地址从 HTTPS 切换为 SSH。",
    mode: "sim",
    seedId: "with-remote",
    steps: [
      {
        id: "s06-remote-v",
        validatorId: "w4-remote-v",
        title: "查看当前远程",
        instruction: "输入 git remote -v，确认当前 origin 地址。",
        commandHint: "git remote -v",
        riskLevel: "basic",
      },
      {
        id: "s06-remote-set-url",
        validatorId: "w12-remote-set-url",
        title: "切换为 SSH 地址",
        instruction: "输入 git remote set-url origin git@github.com:YOUR_USERNAME/YOUR_REPO.git",
        commandHint: "git remote set-url origin git@github.com:YOUR_USERNAME/YOUR_REPO.git",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario07",
    title: "S07 - 开分支做功能",
    description: "练习创建与切换分支，让 main 保持稳定可发布。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s07-init",
        validatorId: "w6-init",
        title: "准备仓库",
        instruction: "输入 git init 并至少完成一次提交（init -> add . -> commit）。",
        commandHint: "git init",
        checkpoints: [
          { id: "s07-init-init", title: "初始化仓库", validatorId: "cp-init" },
          { id: "s07-init-add", title: "执行一次 add", validatorId: "cp-add-any" },
          { id: "s07-init-commit", title: "完成一次 commit", validatorId: "cp-commit-any" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s07-branch-list",
        validatorId: "w6-branch-list",
        title: "列出分支",
        instruction: "输入 git branch 查看本地分支。",
        commandHint: "git branch",
        riskLevel: "basic",
      },
      {
        id: "s07-branch-create",
        validatorId: "w6-branch-create",
        title: "创建分支",
        instruction: "输入 git branch feature。",
        commandHint: "git branch feature",
        riskLevel: "basic",
      },
      {
        id: "s07-switch-c",
        validatorId: "w6-switch-c",
        title: "创建并切换 (switch)",
        instruction: "输入 git switch -c hotfix。",
        commandHint: "git switch -c hotfix",
        riskLevel: "basic",
      },
      {
        id: "s07-checkout-b",
        validatorId: "w6-checkout-b",
        title: "创建并切换 (checkout)",
        instruction: "输入 git checkout -b develop。",
        commandHint: "git checkout -b develop",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario08",
    title: "S08 - 合并或变基",
    description: "理解 merge 与 rebase 对分支历史的影响。",
    mode: "sim",
    seedId: "two-branches",
    steps: [
      {
        id: "s08-setup",
        validatorId: "w7-setup",
        title: "准备分支",
        instruction: "完成 init、提交，并创建 feature 分支（git branch feature）。",
        commandHint: "git branch feature",
        checkpoints: [
          { id: "s08-setup-init", title: "初始化仓库", validatorId: "cp-init" },
          { id: "s08-setup-add", title: "执行一次 add", validatorId: "cp-add-any" },
          { id: "s08-setup-commit", title: "完成一次 commit", validatorId: "cp-commit-any" },
          { id: "s08-setup-branch", title: "创建 feature 分支", validatorId: "cp-branch-feature" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s08-merge",
        validatorId: "w7-merge",
        title: "合并分支",
        instruction: "切换到 feature 后输入 git merge main。",
        commandHint: "git merge main",
        riskLevel: "basic",
      },
      {
        id: "s08-rebase",
        validatorId: "w7-rebase",
        title: "变基分支",
        instruction: "输入 git rebase main，观察指针重定位。",
        commandHint: "git rebase main",
        riskLevel: "advanced",
        riskNote: "rebase 会改写历史，公共分支慎用。",
      },
    ],
  },
  {
    id: "scenario09",
    title: "S09 - 拉队友最新代码",
    description: "开工前同步远程，理解 fetch / pull / pull --rebase。",
    mode: "sim",
    seedId: "with-remote",
    steps: [
      {
        id: "s09-fetch-origin",
        validatorId: "w12-fetch",
        title: "同步远程引用",
        instruction: "输入 git fetch origin。",
        commandHint: "git fetch origin",
        riskLevel: "basic",
      },
      {
        id: "s09-pull",
        validatorId: "w3-pull",
        title: "拉取并合并",
        instruction: "输入 git pull，拉取并合并到当前分支。",
        commandHint: "git pull",
        riskLevel: "basic",
      },
      {
        id: "s09-pull-rebase",
        validatorId: "w3-pull-rebase",
        title: "拉取并变基",
        instruction: "输入 git pull --rebase，在 rebase 工作流下保持线性历史。",
        commandHint: "git pull --rebase",
        riskLevel: "advanced",
        riskNote: "仅在团队约定使用 rebase 工作流时执行。",
      },
    ],
  },
  {
    id: "scenario10",
    title: "S10 - PR 前整理历史",
    description: "提 PR 前先 fetch、rebase 到最新 main，并检查提交范围。",
    mode: "sim",
    seedId: "with-remote",
    steps: [
      {
        id: "s10-fetch-origin",
        validatorId: "w12-fetch",
        title: "获取最新远程",
        instruction: "输入 git fetch origin。",
        commandHint: "git fetch origin",
        riskLevel: "basic",
      },
      {
        id: "s10-rebase-origin-main",
        validatorId: "w12-rebase-origin",
        title: "变基到最新 main",
        instruction: "输入 git rebase origin/main。",
        commandHint: "git rebase origin/main",
        riskLevel: "advanced",
        riskNote: "仅在个人分支且团队允许 rebase 时使用。",
      },
      {
        id: "s10-log-range",
        validatorId: "w12-log-range",
        title: "检查提交范围",
        instruction: "输入 git log origin/main..HEAD，确认 PR 只包含你的提交。",
        commandHint: "git log origin/main..HEAD",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario11",
    title: "S11 - 被打断暂存现场",
    description: "用 stash 临时收起工作区改动，稍后恢复继续开发。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s11-init",
        validatorId: "w8-init",
        title: "准备改动",
        instruction: "输入 git init，确保工作区有未提交改动（默认有 README.md）。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "s11-stash",
        validatorId: "w8-stash",
        title: "收起改动",
        instruction: "输入 git stash，把工作区改动暂存起来。",
        commandHint: "git stash",
        riskLevel: "basic",
      },
      {
        id: "s11-stash-list",
        validatorId: "w8-stash-list",
        title: "查看 stash",
        instruction: "输入 git stash list。",
        commandHint: "git stash list",
        riskLevel: "basic",
      },
      {
        id: "s11-stash-pop",
        validatorId: "w8-stash-pop",
        title: "恢复 stash",
        instruction: "输入 git stash pop，恢复最近一次暂存。",
        commandHint: "git stash pop",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "scenario12",
    title: "S12 - 撤销还没推送的改动",
    description: "学习 restore 与 reset 的温和撤销方式。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s12-init-commit",
        validatorId: "w9-init-commit",
        title: "建立基线提交",
        instruction: "依次完成 git init -> git add . -> git commit -m \"base\"。",
        commandHint: 'git commit -m "base"',
        checkpoints: [
          { id: "s12-init-commit-init", title: "初始化仓库", validatorId: "cp-init" },
          { id: "s12-init-commit-add", title: "执行 git add", validatorId: "cp-add-any" },
          { id: "s12-init-commit-commit", title: "完成基线提交", validatorId: "cp-commit-any" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s12-restore-staged",
        validatorId: "w9-restore-staged",
        title: "取消暂存",
        instruction: "先 git add README.md，再执行 git restore --staged README.md。",
        commandHint: "git restore --staged README.md",
        checkpoints: [
          { id: "s12-restore-staged-add", title: "先暂存 README.md", validatorId: "cp-add-readme" },
          { id: "s12-restore-staged-restore", title: "再取消暂存", validatorId: "cp-restore-staged-readme" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s12-restore-file",
        validatorId: "w9-restore-file",
        title: "丢弃工作区修改",
        instruction: "输入 git restore README.md，丢弃未提交修改。",
        commandHint: "git restore README.md",
        riskLevel: "basic",
      },
      {
        id: "s12-reset-head",
        validatorId: "w9-reset-head",
        title: "取消暂存（旧写法）",
        instruction: "输入 git reset HEAD README.md（等效 restore --staged）。",
        commandHint: "git reset HEAD README.md",
        riskLevel: "basic",
      },
      {
        id: "s12-reset-soft",
        validatorId: "w9-reset-soft",
        title: "软回退",
        instruction: "输入 git reset --soft HEAD~1，回退提交但保留暂存。",
        commandHint: "git reset --soft HEAD~1",
        riskLevel: "advanced",
        riskNote: "仅适用于未 push 的本地提交。",
      },
    ],
  },
  {
    id: "scenario13",
    title: "S13 - 已推送后的安全回滚",
    description: "对比 amend、revert 与 reset --hard 的适用场景和风险。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s13-setup",
        validatorId: "w10-setup",
        title: "准备提交",
        instruction: "完成 init -> add . -> commit -m \"release\"。",
        commandHint: 'git commit -m "release"',
        checkpoints: [
          { id: "s13-setup-init", title: "初始化仓库", validatorId: "cp-init" },
          { id: "s13-setup-add", title: "执行 git add", validatorId: "cp-add-any" },
          { id: "s13-setup-commit", title: "完成 release 提交", validatorId: "cp-commit-any" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s13-amend",
        validatorId: "w10-amend",
        title: "修改最近提交",
        instruction: "输入 git commit --amend -m \"release v2\"。",
        commandHint: 'git commit --amend -m "release v2"',
        riskLevel: "advanced",
        riskNote: "仅适用于未 push 的最后一次提交。",
      },
      {
        id: "s13-revert",
        validatorId: "w10-revert",
        title: "反向提交回滚",
        instruction: "输入 git revert HEAD（团队协作推荐方式）。",
        commandHint: "git revert HEAD",
        riskLevel: "advanced",
        riskNote: "已 push 历史优先使用 revert，而不是 reset --hard。",
      },
      {
        id: "s13-reset-hard",
        validatorId: "w10-reset-hard",
        title: "硬回退（危险）",
        instruction: "输入 git reset --hard HEAD~1，体验高风险回退。",
        commandHint: "git reset --hard HEAD~1",
        riskLevel: "danger",
        riskNote: "危险：会丢弃提交与改动。公共分支请改用 git revert。",
      },
    ],
  },
  {
    id: "scenario14",
    title: "S14 - 忽略不该提交的文件",
    description: "配置 .gitignore，并修复误跟踪文件。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "s14-init",
        validatorId: "w11-init",
        title: "初始化",
        instruction: "输入 git init。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "s14-gitignore",
        validatorId: "w11-gitignore",
        title: "添加忽略文件",
        instruction: "输入 git add .gitignore，创建忽略规则。",
        commandHint: "git add .gitignore",
        riskLevel: "basic",
      },
      {
        id: "s14-add-tracked",
        validatorId: "w11-add-tracked",
        title: "暂存业务文件",
        instruction: "输入 git add README.md 并 commit -m \"track files\"。",
        commandHint: 'git commit -m "track files"',
        checkpoints: [
          { id: "s14-add-tracked-add", title: "先暂存 README.md", validatorId: "cp-add-readme" },
          { id: "s14-add-tracked-commit", title: "再提交业务文件", validatorId: "cp-commit-any" },
        ],
        riskLevel: "basic",
      },
      {
        id: "s14-rm-cached",
        validatorId: "w11-rm-cached",
        title: "停止跟踪",
        instruction: "输入 git rm -r --cached README.md，保留文件但停止跟踪。",
        commandHint: "git rm -r --cached README.md",
        riskLevel: "advanced",
        riskNote: "配合 .gitignore 修正误跟踪文件。",
      },
    ],
  },
  {
    id: "scenario15",
    title: "S15 - 真实环境演练",
    description: "在 Real 模式完成 init -> add -> commit -> log，迁移 Sim 所学。",
    mode: "real",
    seedId: "empty",
    steps: [
      {
        id: "s15-init",
        validatorId: "w13-init",
        title: "真实引擎初始化",
        instruction: "输入 git init。远端/撤销等高级命令请回到 Sim 关卡练习。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "s15-add",
        validatorId: "w13-add",
        title: "真实暂存",
        instruction: "输入 git add demo.txt（Real 模式会自动创建演示文件）。",
        commandHint: "git add demo.txt",
        riskLevel: "basic",
      },
      {
        id: "s15-commit",
        validatorId: "w13-commit",
        title: "真实提交",
        instruction: "输入 git commit -m \"real sandbox\"。",
        commandHint: 'git commit -m "real sandbox"',
        riskLevel: "basic",
      },
      {
        id: "s15-log",
        validatorId: "w13-log",
        title: "真实历史",
        instruction: "输入 git log，确认浏览器内真实 Git 已产生提交。",
        commandHint: "git log",
        riskLevel: "basic",
      },
    ],
  },
];
