import type { LessonWorld } from "./types";

export const worlds: LessonWorld[] = [
  {
    id: "world1",
    title: "World 1 - 初始化仓库",
    description: "从 git init 开始，完成第一次提交并查看历史。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w1-init",
        validatorId: "w1-init",
        title: "初始化仓库",
        instruction: "输入 git init，在本地创建 Git 仓库。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w1-add-all",
        validatorId: "w1-add-all",
        title: "暂存所有文件",
        instruction: "输入 git add .，把当前目录改动加入暂存区。",
        commandHint: "git add .",
        riskLevel: "basic",
      },
      {
        id: "w1-commit",
        validatorId: "w1-commit",
        title: "首次提交",
        instruction: "输入 git commit -m \"first commit\"，创建第一个提交。",
        commandHint: 'git commit -m "first commit"',
        riskLevel: "basic",
      },
      {
        id: "w1-log-oneline",
        validatorId: "w1-log-oneline",
        title: "单行历史",
        instruction: "输入 git log --oneline，用简洁格式查看提交历史。",
        commandHint: "git log --oneline",
        riskLevel: "basic",
      },
      {
        id: "w1-status",
        validatorId: "w1-status",
        title: "确认状态",
        instruction: "输入 git status，确认工作区是否干净。",
        commandHint: "git status",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world2",
    title: "World 2 - 连接 GitHub",
    description: "学习 branch -M、remote add 与首次 push -u。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w2-init",
        validatorId: "w2-init",
        title: "准备仓库",
        instruction: "先执行 git init，再 add/commit（可重复本关前几步命令）。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w2-branch-m",
        validatorId: "w2-branch-m",
        title: "统一默认分支",
        instruction: "输入 git branch -M main，把当前分支命名为 main。",
        commandHint: "git branch -M main",
        riskLevel: "basic",
      },
      {
        id: "w2-remote-add",
        validatorId: "w2-remote-add",
        title: "关联远程",
        instruction: "输入 git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        commandHint: "git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        riskLevel: "basic",
      },
      {
        id: "w2-push-u",
        validatorId: "w2-push-u",
        title: "首次推送",
        instruction: "输入 git push -u origin main，建立上游跟踪关系。",
        commandHint: "git push -u origin main",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world3",
    title: "World 3 - 克隆与同步",
    description: "掌握 clone、fetch、pull 与 pull --rebase。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w3-clone",
        validatorId: "w3-clone",
        title: "克隆仓库",
        instruction: "输入 git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        commandHint: "git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git",
        riskLevel: "basic",
      },
      {
        id: "w3-fetch",
        validatorId: "w3-fetch",
        title: "拉取远端对象",
        instruction: "输入 git fetch，获取远程更新但不自动合并。",
        commandHint: "git fetch",
        riskLevel: "basic",
      },
      {
        id: "w3-pull",
        validatorId: "w3-pull",
        title: "拉取并合并",
        instruction: "输入 git pull，拉取并合并到当前分支。",
        commandHint: "git pull",
        riskLevel: "basic",
      },
      {
        id: "w3-pull-rebase",
        validatorId: "w3-pull-rebase",
        title: "拉取并变基",
        instruction: "输入 git pull --rebase，在团队约定允许时使用线性历史。",
        commandHint: "git pull --rebase",
        riskLevel: "advanced",
        riskNote: "仅在团队约定使用 rebase 时执行。",
      },
    ],
  },
  {
    id: "world4",
    title: "World 4 - 状态与诊断",
    description: "用 status、diff、remote -v 诊断仓库状态。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w4-init",
        validatorId: "w4-init",
        title: "准备环境",
        instruction: "输入 git init 开始本关练习。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w4-status",
        validatorId: "w4-status",
        title: "查看状态",
        instruction: "输入 git status，查看工作区与暂存区。",
        commandHint: "git status",
        riskLevel: "basic",
      },
      {
        id: "w4-diff",
        validatorId: "w4-diff",
        title: "未暂存差异",
        instruction: "输入 git diff，查看尚未暂存的改动。",
        commandHint: "git diff",
        riskLevel: "basic",
      },
      {
        id: "w4-diff-staged",
        validatorId: "w4-diff-staged",
        title: "已暂存差异",
        instruction: "先 git add README.md，再执行 git diff --staged。",
        commandHint: "git diff --staged",
        riskLevel: "basic",
      },
      {
        id: "w4-remote-v",
        validatorId: "w4-remote-v",
        title: "查看远程地址",
        instruction: "输入 git remote add origin https://github.com/demo/repo.git，再执行 git remote -v。",
        commandHint: "git remote -v",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world5",
    title: "World 5 - 提交流程",
    description: "练习 add、commit -m 与 commit -am 的常见提交流程。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w5-init",
        validatorId: "w5-init",
        title: "初始化",
        instruction: "输入 git init。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w5-add-file",
        validatorId: "w5-add-file",
        title: "暂存单文件",
        instruction: "输入 git add README.md。",
        commandHint: "git add README.md",
        riskLevel: "basic",
      },
      {
        id: "w5-commit-m",
        validatorId: "w5-commit-m",
        title: "带说明提交",
        instruction: "输入 git commit -m \"init\"。",
        commandHint: 'git commit -m "init"',
        riskLevel: "basic",
      },
      {
        id: "w5-add-all",
        validatorId: "w5-add-all",
        title: "暂存全部",
        instruction: "输入 git add .（本关会模拟新的工作区改动）。",
        commandHint: "git add .",
        riskLevel: "basic",
      },
      {
        id: "w5-commit-am",
        validatorId: "w5-commit-am",
        title: "跳过 add 提交",
        instruction: "输入 git commit -am \"quick update\"，对已跟踪文件直接提交。",
        commandHint: 'git commit -am "quick update"',
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world6",
    title: "World 6 - 分支操作",
    description: "掌握 branch、checkout、switch 与创建并切换。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w6-init",
        validatorId: "w6-init",
        title: "准备仓库",
        instruction: "输入 git init 并至少完成一次提交（init -> add . -> commit）。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w6-branch-list",
        validatorId: "w6-branch-list",
        title: "列出分支",
        instruction: "输入 git branch 查看本地分支。",
        commandHint: "git branch",
        riskLevel: "basic",
      },
      {
        id: "w6-branch-create",
        validatorId: "w6-branch-create",
        title: "创建分支",
        instruction: "输入 git branch feature。",
        commandHint: "git branch feature",
        riskLevel: "basic",
      },
      {
        id: "w6-switch-c",
        validatorId: "w6-switch-c",
        title: "创建并切换 (switch)",
        instruction: "输入 git switch -c hotfix。",
        commandHint: "git switch -c hotfix",
        riskLevel: "basic",
      },
      {
        id: "w6-checkout-b",
        validatorId: "w6-checkout-b",
        title: "创建并切换 (checkout)",
        instruction: "输入 git checkout -b develop。",
        commandHint: "git checkout -b develop",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world7",
    title: "World 7 - 合并与变基",
    description: "理解 merge 与 rebase 对分支历史的影响。",
    mode: "sim",
    seedId: "two-branches",
    steps: [
      {
        id: "w7-setup",
        validatorId: "w7-setup",
        title: "准备分支",
        instruction: "完成 init、提交，并创建 feature 分支（git branch feature）。",
        commandHint: "git branch feature",
        riskLevel: "basic",
      },
      {
        id: "w7-merge",
        validatorId: "w7-merge",
        title: "合并分支",
        instruction: "切换到 feature 后输入 git merge main。",
        commandHint: "git merge main",
        riskLevel: "basic",
      },
      {
        id: "w7-rebase",
        validatorId: "w7-rebase",
        title: "变基分支",
        instruction: "输入 git rebase main，观察指针重定位。",
        commandHint: "git rebase main",
        riskLevel: "advanced",
        riskNote: "rebase 会改写历史，公共分支慎用。",
      },
    ],
  },
  {
    id: "world8",
    title: "World 8 - 暂存现场",
    description: "用 stash 临时保存工作区，稍后恢复。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w8-init",
        validatorId: "w8-init",
        title: "准备改动",
        instruction: "输入 git init，确保工作区有未提交改动（默认有 README.md）。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w8-stash",
        validatorId: "w8-stash",
        title: "收起改动",
        instruction: "输入 git stash，把工作区改动暂存起来。",
        commandHint: "git stash",
        riskLevel: "basic",
      },
      {
        id: "w8-stash-list",
        validatorId: "w8-stash-list",
        title: "查看 stash",
        instruction: "输入 git stash list。",
        commandHint: "git stash list",
        riskLevel: "basic",
      },
      {
        id: "w8-stash-pop",
        validatorId: "w8-stash-pop",
        title: "恢复 stash",
        instruction: "输入 git stash pop，恢复最近一次暂存。",
        commandHint: "git stash pop",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world9",
    title: "World 9 - 撤销基础",
    description: "学习 restore 与 reset 的温和撤销方式。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w9-init-commit",
        validatorId: "w9-init-commit",
        title: "建立基线提交",
        instruction: "依次完成 git init -> git add . -> git commit -m \"base\"。",
        commandHint: 'git commit -m "base"',
        riskLevel: "basic",
      },
      {
        id: "w9-restore-staged",
        validatorId: "w9-restore-staged",
        title: "取消暂存",
        instruction: "先 git add README.md，再执行 git restore --staged README.md。",
        commandHint: "git restore --staged README.md",
        riskLevel: "basic",
      },
      {
        id: "w9-restore-file",
        validatorId: "w9-restore-file",
        title: "丢弃工作区修改",
        instruction: "输入 git restore README.md，丢弃未提交修改。",
        commandHint: "git restore README.md",
        riskLevel: "basic",
      },
      {
        id: "w9-reset-head",
        validatorId: "w9-reset-head",
        title: "取消暂存（旧写法）",
        instruction: "输入 git reset HEAD README.md（等效 restore --staged）。",
        commandHint: "git reset HEAD README.md",
        riskLevel: "basic",
      },
      {
        id: "w9-reset-soft",
        validatorId: "w9-reset-soft",
        title: "软回退",
        instruction: "输入 git reset --soft HEAD~1，回退提交但保留暂存。",
        commandHint: "git reset --soft HEAD~1",
        riskLevel: "advanced",
        riskNote: "仅适用于未 push 的本地提交。",
      },
    ],
  },
  {
    id: "world10",
    title: "World 10 - 风险与回滚",
    description: "学习 amend、revert 与高风险 reset --hard。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w10-setup",
        validatorId: "w10-setup",
        title: "准备提交",
        instruction: "完成 init -> add . -> commit -m \"release\"。",
        commandHint: 'git commit -m "release"',
        riskLevel: "basic",
      },
      {
        id: "w10-amend",
        validatorId: "w10-amend",
        title: "修改最近提交",
        instruction: "输入 git commit --amend -m \"release v2\"。",
        commandHint: 'git commit --amend -m "release v2"',
        riskLevel: "advanced",
        riskNote: "仅适用于未 push 的最后一次提交。",
      },
      {
        id: "w10-revert",
        validatorId: "w10-revert",
        title: "反向提交回滚",
        instruction: "输入 git revert HEAD（团队协作推荐方式）。",
        commandHint: "git revert HEAD",
        riskLevel: "advanced",
        riskNote: "已 push 历史优先使用 revert，而不是 reset --hard。",
      },
      {
        id: "w10-reset-hard",
        validatorId: "w10-reset-hard",
        title: "硬回退（危险）",
        instruction: "输入 git reset --hard HEAD~1，体验高风险回退。",
        commandHint: "git reset --hard HEAD~1",
        riskLevel: "danger",
        riskNote: "危险：会丢弃提交与改动。公共分支请改用 git revert。",
      },
    ],
  },
  {
    id: "world11",
    title: "World 11 - 忽略规则",
    description: "学习 .gitignore 与停止跟踪已提交文件。",
    mode: "sim",
    seedId: "empty",
    steps: [
      {
        id: "w11-init",
        validatorId: "w11-init",
        title: "初始化",
        instruction: "输入 git init。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w11-gitignore",
        validatorId: "w11-gitignore",
        title: "添加忽略文件",
        instruction: "输入 git add .gitignore，创建忽略规则。",
        commandHint: "git add .gitignore",
        riskLevel: "basic",
      },
      {
        id: "w11-add-tracked",
        validatorId: "w11-add-tracked",
        title: "暂存业务文件",
        instruction: "输入 git add README.md 并 commit -m \"track files\"。",
        commandHint: 'git commit -m "track files"',
        riskLevel: "basic",
      },
      {
        id: "w11-rm-cached",
        validatorId: "w11-rm-cached",
        title: "停止跟踪",
        instruction: "输入 git rm -r --cached README.md，保留文件但停止跟踪。",
        commandHint: "git rm -r --cached README.md",
        riskLevel: "advanced",
        riskNote: "配合 .gitignore 修正误跟踪文件。",
      },
    ],
  },
  {
    id: "world12",
    title: "World 12 - 协作收尾",
    description: "PR 前同步远程、检查差异并更新 remote 地址。",
    mode: "sim",
    seedId: "with-remote",
    steps: [
      {
        id: "w12-setup",
        validatorId: "w12-setup",
        title: "准备远程",
        instruction: "完成 init、提交，并添加 origin 远程。",
        commandHint: "git remote add origin https://github.com/demo/repo.git",
        riskLevel: "basic",
      },
      {
        id: "w12-fetch",
        validatorId: "w12-fetch",
        title: "同步远程",
        instruction: "输入 git fetch origin。",
        commandHint: "git fetch origin",
        riskLevel: "basic",
      },
      {
        id: "w12-rebase-origin",
        validatorId: "w12-rebase-origin",
        title: "变基到远程 main",
        instruction: "输入 git rebase origin/main，保持功能分支线性。",
        commandHint: "git rebase origin/main",
        riskLevel: "advanced",
        riskNote: "仅在个人分支且团队允许 rebase 时使用。",
      },
      {
        id: "w12-log-range",
        validatorId: "w12-log-range",
        title: "查看领先提交",
        instruction: "输入 git log origin/main..HEAD，查看本地多出的提交。",
        commandHint: "git log origin/main..HEAD",
        riskLevel: "basic",
      },
      {
        id: "w12-remote-set-url",
        validatorId: "w12-remote-set-url",
        title: "修改远程地址",
        instruction: "输入 git remote set-url origin git@github.com:YOUR_USERNAME/YOUR_REPO.git",
        commandHint: "git remote set-url origin git@github.com:YOUR_USERNAME/YOUR_REPO.git",
        riskLevel: "basic",
      },
    ],
  },
  {
    id: "world13",
    title: "World 13 - 真实沙盒收官",
    description: "在 Real 模式完成 init -> add -> commit -> log，迁移 Sim 所学。",
    mode: "real",
    seedId: "empty",
    steps: [
      {
        id: "w13-init",
        validatorId: "w13-init",
        title: "真实引擎初始化",
        instruction: "输入 git init。远端/撤销等高级命令请回到 Sim 关卡练习。",
        commandHint: "git init",
        riskLevel: "basic",
      },
      {
        id: "w13-add",
        validatorId: "w13-add",
        title: "真实暂存",
        instruction: "输入 git add demo.txt（Real 模式会自动创建演示文件）。",
        commandHint: "git add demo.txt",
        riskLevel: "basic",
      },
      {
        id: "w13-commit",
        validatorId: "w13-commit",
        title: "真实提交",
        instruction: "输入 git commit -m \"real sandbox\"。",
        commandHint: 'git commit -m "real sandbox"',
        riskLevel: "basic",
      },
      {
        id: "w13-log",
        validatorId: "w13-log",
        title: "真实历史",
        instruction: "输入 git log，确认浏览器内真实 Git 已产生提交。",
        commandHint: "git log",
        riskLevel: "basic",
      },
    ],
  },
];
